### ISSUE TITLE
Add links and pricing scheme

### ISSUE THREAD

**Issue by oolonek** [digital-botanical-gardens-initiative/dendron-dbgi#4]
Hi @mwannier30 

Thanks for the survey you started over here https://github.com/digital-botanical-gardens-initiative/dendron-dbgi/blob/main/vault/database.nocodb.2022.2022-09-22.md

Didn't know about some of these options !
Could you please add these points when reviewing these tools :

- link toward the tool homepage
- open source status
- pricing (you can directly add a link to the pricing page)
- row limitations (I have seen that this was often one if the limits in the paid options)

**Comment by oolonek** [comment]
I stumbled upon this one some day ago I let you have a look if it worth it https://directus.io/

**Comment by mwannier30** [comment]
Thanks, I added some pros and cons also for directus
